project: 
  type: website
  preview: 
    browser: true

website:  
  title: "Rishav Kumar"
  site-url: "https://rishav-kumarr.netlify.app/"
  description: "Let's connect"
  twitter-card: true
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about-me.qmd
      - text: "Published Work"
        menu:
          - text: "Articles"
            href: articles.qmd
          - text: "Documentary"
            href: documentary.qmd
            
      - text: "Personal Project"
        href: project.qmd         

  page-footer: 
    left: "Copyright 2025, Rishav Kumar" 
    right: "Made with support of [SARA](https://sara-edu.netlify.app/)" 
        
format:
  html:
    theme: cyborg
    css: style.css
